### ISSUE TITLE
Image scaling does not apply to contours, markers, trees

### ISSUE THREAD

**Issue by rchristie** [ABI-Software/mbfxml2ex#5]
Must remove the line:
data.process_scaling_and_offset()
I have had this confirmed from MBF:
The scale for x and y in the images element refer to the scale of pixel sizes in model units (e.g. microns per pixel) and zspacing is the spacing of 2-D image planes in those units. They are not for scaling contour, marker, tree and other segmented coordinates.
I don't have an example with an offset, but assume if it is part of images info, it does not apply to the contour etc. either.

**Comment by hsorby** [comment]
Done.
